// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMJt69oW4LKOPnVJmHjBChGRS3YKNLkqA',
    appId: '1:383097108258:web:2025bac72a2367ccfb977b',
    messagingSenderId: '383097108258',
    projectId: 'course-motobike-934ca',
    authDomain: 'course-motobike-934ca.firebaseapp.com',
    storageBucket: 'course-motobike-934ca.appspot.com',
    measurementId: 'G-S22J8ECEM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACZURYb1qpWuNib8Q55his2ovAYSzOUoU',
    appId: '1:383097108258:android:6ee49bdce60c88acfb977b',
    messagingSenderId: '383097108258',
    projectId: 'course-motobike-934ca',
    storageBucket: 'course-motobike-934ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRf5BPHypC5lrRhDSu8b48r1QQH0jwXfs',
    appId: '1:383097108258:ios:680260f1741009edfb977b',
    messagingSenderId: '383097108258',
    projectId: 'course-motobike-934ca',
    storageBucket: 'course-motobike-934ca.appspot.com',
    iosBundleId: 'com.example.couseMotobikeCs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRf5BPHypC5lrRhDSu8b48r1QQH0jwXfs',
    appId: '1:383097108258:ios:680260f1741009edfb977b',
    messagingSenderId: '383097108258',
    projectId: 'course-motobike-934ca',
    storageBucket: 'course-motobike-934ca.appspot.com',
    iosBundleId: 'com.example.couseMotobikeCs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMJt69oW4LKOPnVJmHjBChGRS3YKNLkqA',
    appId: '1:383097108258:web:761365de4093a00efb977b',
    messagingSenderId: '383097108258',
    projectId: 'course-motobike-934ca',
    authDomain: 'course-motobike-934ca.firebaseapp.com',
    storageBucket: 'course-motobike-934ca.appspot.com',
    measurementId: 'G-MGBRYZ98Y0',
  );

}